Repository kubewarden/kubewarden-end-to-end-tests, pull requests merged in 2025-08, with the labels that each got.

#197 Set default OTEL operator version in makefile
  Makefile
  tests/opentelemetry-tests.bats
Labels: kind/tech-debt

#195 Validate github action input
  action.yml
Labels: area/ci

#199 Use hauler manifest in airgap build script
  tests/ginkgo-e2e/scripts/build-airgap
Labels: area/qa
